apiVersion: v1
kind: Pod
metadata:
  name: nginx-busybox-pod
  namespace: hohey
  labels: 
    app: nginx-busybox-pod
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
      - containerPort: 80
    - name: busybox
      image: busybox
      # 같은 Pod 내에 있으니 localhost 내부 포트로 부를 수 있음
      command: ['sh', '-c', 'while true; do wget -qO- http://localhost:80; sleep 5; done']