apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: hohey
spec:
# node를 통해 직접 접근 가능한 타입
# type에는 cluster, ip 등의 type이 있으며 nodeport가 가장 사용 안 하는 것
  type: NodePort
  ports:
  - port: 80 # service port를 의미
    targetPort: 80 # service가 라우팅해줄 대상의 port
    nodePort: 30603
  selector:
  # pod의 labes의 app과 같은 이름을 써야함
  # labels는 service의 라우팅 대상이 되는 이름
  # service의 selector.app을 통해 매핑
  # pod의 labels.app과 service의 selector.app이 일치해야함에 유의
    app: my-nginx
